experiment_name = "unet_dec_21_extended_set"  # configuration name
base_dir = '/exports/csce/eddie/eng/groups/DunnGroup/matthew/models_gelgenie'

[processing]
base_hardware = "EDDIE"   # Where the program is run [EDDIE/PC]
device = "GPU"    # Which processor to use [GPU/CPU]
pe = 1          # How many parallel environments (cores) have been requested alongside this job
memory = 64     # Required memory per core in GBytes

[data]
n_channels = 1 # channels to output to model
batch_size = 2  # Batch size for dataloader
num_workers = 1 # parallel threads to use to speed up data processing

dir_train_mask = [
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/lsdb_gels/masks',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/nathan_gels/masks',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/matthew_gels/masks',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/matthew_gels_2/masks',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/lsdb_gels/val_masks',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/nathan_gels/val_masks',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/matthew_gels/val_masks',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/matthew_gels_2/val_masks',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/quantitation_ladder_gels/masks',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/quantitation_ladder_gels/val_masks']

dir_train_img = [
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/lsdb_gels/images',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/nathan_gels/images',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/matthew_gels/images',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/matthew_gels_2/images',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/lsdb_gels/val_images',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/nathan_gels/val_images',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/matthew_gels/val_images',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/matthew_gels_2/val_images',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/quantitation_ladder_gels/images',
    '/exports/csce/eddie/eng/groups/DunnGroup/matthew/gel_data/quantitation_ladder_gels/val_images'
]

dir_val_img = []
dir_val_mask = []

split_training_dataset = false
apply_augmentations = true
weak_augmentations = false
padding = true
individual_padding = false

[model]
model_name = 'smp_unet'   # model architecture name
classes = 2     # Number of possible segmentation classes
encoder_name = 'resnet18'

[training]
loss = ['dice', 'crossentropy']
lr = 1e-4       # learning rate
epochs = 600     # Number of epochs to run
grad_scaler = true     # Use mixed precision for faster training
load_checkpoint = false    # Load model from a .pth file (Bool/epoch ID)
optimizer_type = 'adam' # Use adam optimizer
save_checkpoint = true # Whether model checkpoints are saved
checkpoint_frequency = 1 # How often checkpoints are saved (per epoch)
model_cleanup_frequency = 20 # How often old checkpoints are deleted (in epochs)
wandb_track = true # Whether to track training with wandb
scheduler_type = 'CosineAnnealingWarmRestarts'
[training.scheduler_specs]
restart_period = 100
